name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: 0.8.0+1
  google_sign_in: 4.0.1
  flutter_slidable: "^0.4.9"
  photo_view: 0.2.2
  zoomable_image: 1.3.1
  flutter_advanced_networkimage: 0.4.13
  cached_network_image: ^0.7.0
  flutter_speed_dial: ^1.0.9
  badges: ^1.0.3



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cloud_firestore: 0.9.0
  firebase_storage: ^2.1.0
  image_picker: ^0.5.0
  uuid: 2.0.0
  rxdart: ^0.21.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/pinkB.jpg
    - assets/images/pinkBG.jpg
    - assets/images/blackDresses.png
    - assets/images/fb.png
    - assets/images/fb2.png
    - assets/images/google.png
    - assets/images/image_error.png
    - assets/images/biela.jpg
    - assets/images/biela2.jpg




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
#   example:
  fonts:
    - family: Alyfe_Demo
      fonts:
        - asset: assets/font/Alyfe_Demo.ttf
    - family: Dancing_Script
      fonts:
        - asset: assets/font/DancingScript-Bold.ttf
        - asset: assets/font/DancingScript-Regular.ttf
    - family: Amagh Demo
      fonts:
        - asset: assets/font/Amagh Demo.ttf
    - family: Pacifico
      fonts:
        - asset: assets/font/Pacifico-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/untitled.png"
  image_path_android: "assets/launcher/untitled.png"
